### ISSUE TITLE
Stream inputs?

### ISSUE THREAD

**Issue by positlabs** [Rodeoclash/ffmpeg-inline#5]
Does ffmpeg-inline support stream inputs (e.g. from getUserMedia)?

**Comment by Rodeoclash** [comment]
I haven't tested it with streams, I don't have any experience with using them with ffmpeg.

The processing essentially works by sharing the virtual file system with ffmpeg. If ffmpeg can watch and file and stream it, you should be able to keep writing data to it.

Let me know how you go.

**Comment by positlabs** [comment]
Unfortunately I can't explore this further, so I'm closing the ticket.
